name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up temurin 20
      uses: actions/setup-java@v3
      with:
        java-version: '20.0.1+9'
        distribution: 'temurin'
        cache: maven
    - name: Test project
      run: mvn -B test --file pom.xml
